name: yarn-install
description: cached yarn install

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache path
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install modules
      run: yarn
      shell: bash
